default: &default
  encoding: unicode
  pool: 5
  timeout: 5000

development:
   <<: *default
   adapter: sqlite3
   database: db/development.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: 'postgres'
